# Generated by Django 5.0.6 on 2024-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='features/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='collab',
            name='image',
            field=models.ImageField(upload_to='collabs/% Y/% m/% d/'),
        ),
    ]
