# Generated by Django 5.0.6 on 2024-06-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_feature_alter_collab_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='image',
        ),
    ]
