# Generated by Django 5.0.6 on 2024-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
