# Generated by Django 5.0.6 on 2024-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
