# Generated by Django 5.0.6 on 2024-06-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.event'),
            preserve_default=False,
        ),
    ]
