# Generated by Django 5.0.6 on 2024-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_highlight_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Kathmandu', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collab',
            name='image',
            field=models.ImageField(upload_to='collabs/'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(upload_to='highlights/'),
        ),
    ]
