# Generated by Django 5.0.6 on 2024-06-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='social',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.sociallink'),
            preserve_default=False,
        ),
    ]
