# Generated by Django 5.0.6 on 2024-06-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_member_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='social',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.member'),
            preserve_default=False,
        ),
    ]
