# Generated by Django 5.0.6 on 2024-06-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_socialicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialicon',
            name='icon',
            field=models.CharField(max_length=255),
        ),
    ]
