# Generated by Django 5.0.6 on 2024-06-17 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_socialicon_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.socialicon'),
            preserve_default=False,
        ),
    ]
