# Generated by Django 5.0.6 on 2024-06-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_sociallink_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='name',
        ),
    ]
