# Generated by Django 5.0.6 on 2024-06-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_contact_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Goal',
        ),
    ]
