# Generated by Django 5.0.6 on 2024-06-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
