# Generated by Django 5.0.6 on 2024-06-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_author_remove_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.author'),
            preserve_default=False,
        ),
    ]
