# Generated by Django 5.0.6 on 2024-06-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
