# Generated by Django 5.0.6 on 2024-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_tag_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
