# Generated by Django 5.0.6 on 2024-07-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_rename_comment_comment_content_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
