# Generated by Django 5.0.6 on 2024-07-02 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
