# Generated by Django 5.0.6 on 2024-07-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_subscribe_alter_blog_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
    ]
