# Generated by Django 5.0.6 on 2024-07-05 09:41

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='social_links',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.sociallink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.sociallink'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
