# Generated by Django 5.0.6 on 2024-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='bootcamp', max_length=200, null=True),
        ),
    ]
