# Generated by Django 4.2.19 on 2025-02-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_member_profile_profile_author_profile_member'),
        ('contact', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_socials', to='team.member'),
        ),
    ]
