# Generated by Django 4.2.19 on 2025-02-23 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_remove_member_profile_profile_author_profile_member'),
        ('contact', '0003_alter_sociallink_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_socials', to='team.member'),
        ),
    ]
