# Generated by Django 4.2.19 on 2025-02-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_sociallink_author_alter_sociallink_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.socialicon'),
        ),
    ]
