# Generated by Django 4.2.19 on 2025-02-23 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0005_alter_sociallink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_socials', to=settings.AUTH_USER_MODEL),
        ),
    ]
