# Generated by Django 4.2.19 on 2025-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_sociallink_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemeta',
            name='home_banner',
            field=models.ImageField(blank=True, null=True, upload_to='home/r'),
        ),
    ]
