# Generated by Django 4.2.19 on 2025-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='feedbacks/'),
        ),
    ]
