# Generated by Django 4.2.19 on 2025-02-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_feedback_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureimage',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='home.feature'),
        ),
    ]
