# Generated by Django 4.2.19 on 2025-02-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
