# Generated by Django 4.2.19 on 2025-02-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_member_profile_profile_author_profile_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
