# Generated by Django 4.2.19 on 2025-02-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_member_slug_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_link',
        ),
    ]
