# Generated by Django 4.2.19 on 2025-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_profile_social_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
